### ISSUE TITLE
Demo, mix dev, GET 127.0.0.1:4000/dev/assets/admin.css 404

### ISSUE THREAD

**Issue by Neophen** [BeaconCMS/beacon#105]
Hey trying to launch the demo:

- mix setup
- mix dev
- i get the following error

```
GET http://127.0.0.1:4000/dev/assets/admin.css net::ERR_ABORTED 404 (Not Found)
```

The `admin.css` does exist in `priv/dev/static/assets/admin.css` so not sure what else could be happening here?

**Comment by leandrocp** [comment]
Hi @Neophen can you please update with latest changes? JS and CSS including Tailwind are injected into the pages.

**Comment by leandrocp** [comment]
I can't reproduce it locally, it should be fixed on main. Thanks!

**Comment by leandrocp** [comment]
Hi @Neophen I was able to reproduce it and pushed a fix https://github.com/BeaconCMS/beacon/pull/111/commits/e5a8e1f72b0584cfdf88e9acb3386957f80f8730
