### ISSUE TITLE
Custom live view socket path

### ISSUE THREAD

**Issue by leandrocp** [BeaconCMS/beacon#106]
Currently it's connecting to the live socket provided by the host application at `/live` but that may not be case for every app and we want to support custom paths. For that an option `live_socket_path` is provided on `beacon_site` router macro but it has no effect currently (it's not implemented) https://github.com/BeaconCMS/beacon/blob/924202e757243b941154e576b18c13d447829ca0/lib/beacon/router.ex#L61

That value has to be fetched and injected into the runtime layout https://github.com/BeaconCMS/beacon/blob/924202e757243b941154e576b18c13d447829ca0/lib/beacon_web/components/layouts/runtime.html.heex so it can be passed to live socket https://github.com/BeaconCMS/beacon/blob/924202e757243b941154e576b18c13d447829ca0/priv/assets/js/app.js#L4-L7

Similar to how it's done on LiveDashboard.

**Comment by lucas-cegatti** [comment]
@leandrocp I'll work on this issue.
