### ISSUE TITLE
Core -> Asset Manager -> Image Optimization: Converting to .WEBP

### ISSUE THREAD

**Issue by bcardarella** [BeaconCMS/beacon#124]
When uploading images we should force an optimization process

1. convert all image types to webp format
2. output several image sizes and serve with `srcset`

I may be dating myself but is Imagemagick still the best way to do this?

FROM MEETING FEB 27 2023:
As discussed in a meeting we have to do next:
- [x] Brute force all images in S3 (basic script hitting images one-by-one, etc) for the DY.COM
- [x] Convert to .webp
- [x] Constrain to size
- [x] Constrain on width to preserve aspect ratio
This is not the paved path - trying to get to launch
If an image has a width under the constraint, don’t touch it other than convert it to .webp
Width max: 2880
Maintain aspect ratio at 85% quality

FYI @schrockwell @leandrocp @xn

**Comment by AZholtkevych** [comment]
@bcardarella I'm suggesting postponing this to Q2. What do you think?

**Comment by leandrocp** [comment]
Some extra notes for development:

- Whatever tool we choose, it must be installed in the Dockerfile. Need to updated guides.
- Uploading assets is performed at https://github.com/BeaconCMS/beacon/blob/dc9572d7055ec27b7f3ee1d6675f189d03616e02/lib/beacon/admin/media_library.ex#L57
- The entry point for displaying images are componentes, defined at https://github.com/BeaconCMS/beacon/blob/dc9572d7055ec27b7f3ee1d6675f189d03616e02/lib/beacon_web/components/components.ex#L22

**Comment by leandrocp** [comment]
> is Imagemagick still the best way to do this?

https://developers.google.com/speed/webp/docs/cwebp may be a better fit.

**Comment by AZholtkevych** [comment]
As discussed in a meeting Feb 27 2023 we have to do next things:
- [ ] Brute force all images in S3 (basic script hitting images one-by-one, etc)
- [ ] Convert to .webp
- [ ] Constrain to size
- [ ] Constrain on width to preserve aspect ratio
This is not the paved path - trying to get to launch
If an image has a width under the constraint, don’t touch other than convert it to .webp
Width max: 2880
Maintain aspect ratio at 85% quality

FYI @schrockwell
