### ISSUE TITLE
Core -> Extension: page_title/2 callback silently swallows errors

### ISSUE THREAD

**Issue by schrockwell** [BeaconCMS/beacon#157]
If the user-provided data source raises an error in its implementation of `Beacon.DataSource.Behaviour.page_title/2`, there is no indication that an exception has occurred:

https://github.com/BeaconCMS/beacon/blob/7790eb72769a026c0bdfc3167aab394a9b73ce91/lib/beacon/data_source.ex#L46-L47

We want to change that to `reraise` the exception `Beacon.DataSourceError` providing a meaningful message similar to https://github.com/BeaconCMS/beacon/blob/7790eb72769a026c0bdfc3167aab394a9b73ce91/lib/beacon/lifecycle.ex#L163-L168

**Comment by polvalente** [comment]
Looking into this
