### ISSUE TITLE
Core -> Hosting and Tenant: Compress CSS and JSS using Brotli

### ISSUE THREAD

**Issue by leandrocp** [BeaconCMS/beacon#159]
We want to compress assets using [brotli](https://web.dev/reduce-network-payloads-using-text-compression/) which is [widely supported](https://caniuse.com/?search=brotli) and performs better than gzip.

Currently Beacon compress css and jss using gzip:

https://github.com/BeaconCMS/beacon/blob/7790eb72769a026c0bdfc3167aab394a9b73ce91/lib/beacon/runtime_css.ex#L27

https://github.com/BeaconCMS/beacon/blob/7790eb72769a026c0bdfc3167aab394a9b73ce91/lib/beacon/runtime_js.ex#L45

And serve those assets with proper content encoding:
 https://github.com/BeaconCMS/beacon/blob/7790eb72769a026c0bdfc3167aab394a9b73ce91/lib/beacon_web/controllers/assets_controller.ex#L23

Replace with brotli.

Ref https://github.com/BeaconCMS/beacon/pull/158

**Comment by stefholbrook** [comment]
Looking into this 👀
