### ISSUE TITLE
Serve JS

### ISSUE THREAD

**Issue by AZholtkevych** [BeaconCMS/beacon#176]
We can't pre build JS assets because the host application may be running in a different Phoenix version causing a mismatch and the client may not work. To have full control over the build and minification we could require esbuild at runtime like we do for tailwind-cli but we can postpone it because the only dep that doesn't have a min version is phoenix_html which is very small.

- [x] Build on boot and store on ets to avoid builds for first time requests
- [x] Merge host app's js deps + beacon js
- [x] Serve with cache
- [x] Requests in the same live session
- [x] Compress
- [x] Admin

**Comment by leandrocp** [comment]
Archived, can be closed.
