### ISSUE TITLE
Admin -> Editor: Monaco editor integration

### ISSUE THREAD

**Issue by leandrocp** [BeaconCMS/beacon#189]
Load an instance of https://github.com/microsoft/monaco-editor for `template` fields to write markdown and html.

HEEx may be supported with a custom lang config, but that's not blocking and can be done in a following PR.

**Comment by AZholtkevych** [comment]
Support Elixir, HEEx, HTML, Markdown

**Comment by AZholtkevych** [comment]
@leandrocp appreciate your job and efforts
