### ISSUE TITLE
Admin -> General Improvements: Separate Beacon.Admin namespace into its own app `beacon_admin`

### ISSUE THREAD

**Issue by leandrocp** [BeaconCMS/beacon#190]
For organization purposes and because these apps will have separated release management. Also this is a good opportunity to reorganize Beacon core modules into a well defined public API.

- [x] https://github.com/BeaconCMS/beacon/pull/282
- [x] https://github.com/BeaconCMS/beacon/pull/280
- [x] https://github.com/BeaconCMS/beacon/pull/278

Update: created https://github.com/BeaconCMS/beacon_live_admin

**Comment by AZholtkevych** [comment]
Depends on #227
