### ISSUE TITLE
Core -> Asset Manager -> Image Optimization:: Smart image crop & scale

### ISSUE THREAD

**Issue by AZholtkevych** [BeaconCMS/beacon#198]
As a PO, I would like to have cropping and scaling features with AI. Example and doc could be found here: https://elixirforum.com/t/image-an-image-processing-library-based-upon-vix/47568/104?u=leandrocp

**Comment by AZholtkevych** [comment]
https://elixirforum.com/t/image-an-image-processing-library-based-upon-vix/47568/102

**Comment by xn** [comment]
https://github.com/BeaconCMS/beacon/pull/270
