### ISSUE TITLE
Views

### ISSUE THREAD

**Issue by TheFirstAvenger** [BeaconCMS/beacon#20]
We need a way to dynamically manage View helpers.

Context:
In DeadViews, we have a Controller, a Template, and a View, and helpers for the Template go in the View. In LiveView, these helpers go in the LiveView module. For Beacon, we don't have a LiveView module that the end user can modify, we dynamically load the template based on the path, and #19 will define the event handling.

Instead of having the developer hard code views, we should provide view helpers that are scoped to the template being rendered.

**Comment by TheFirstAvenger** [comment]
@leandrocp Yeah, that is exactly the idea. We could let them specify the arg string so they can build it how they want it (e.g. with pattern matching).

**Comment by leandrocp** [comment]
Gotcha I'm gonna work on it.
