### ISSUE TITLE
Core -> Asset Manager: Serve images from DB with http caching

### ISSUE THREAD

**Issue by AZholtkevych** [BeaconCMS/beacon#212]
We want to serve media library assets with HTTP response caching to avoid unnecessary trips to the database.

Currently those assets are served straight from the database: https://github.com/BeaconCMS/beacon/blob/7790eb72769a026c0bdfc3167aab394a9b73ce91/lib/beacon_web/controllers/media_library_controller.ex#L8-L12

Which is fine for the first request but subsequent requests should leverage caching.

We want to add [ETag](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag) headers to those http responses that can be generated similar to how Plug.Static does it: https://github.com/elixir-plug/plug/blob/3b0609efa32590d1e0bcc551fbf430e0bbcbc55c/lib/plug/static.ex#L364-L365

And handle the request header `If-None-Match` to return 304 if the token matches. 

ETS or DB can be used to store/fetch/compare etag values.

More info at https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag

**Comment by leandrocp** [comment]
Closed by https://github.com/BeaconCMS/beacon/pull/269
