### ISSUE TITLE
General Improvements: Improve home page template created from `beacon.install`

### ISSUE THREAD

**Issue by AZholtkevych** [BeaconCMS/beacon#226]
Improve the home page template created by `beacon.install` https://github.com/BeaconCMS/beacon/blob/7790eb72769a026c0bdfc3167aab394a9b73ce91/priv/templates/install/seeds.exs#L46-L47 to showcase existing features and also improve styling using tailwind classes.

**Comment by leandrocp** [comment]
Seeds will be removed by https://github.com/BeaconCMS/beacon/issues/228
