### ISSUE TITLE
Maybe interesting for front end generation? https://github.com/teleporthq/teleport-code-generators

### ISSUE THREAD

**Issue by davidtew** [BeaconCMS/beacon#243]
This is not actually an issue, but I didn't know where to ask a question so I left it here.  There is a lot of discord chat about this frnt end design system here: https://discord.gg/NZj4fcZh

**Comment by leandrocp** [comment]
Hey @davidtew you can reach out on #beacon-cms channel at https://elixir-lang.slack.com :)

Teleporthq is such a nice tool but a hard requirement for us is to be fully open-source and we're building a similar drag&drop UI builder integrated with Phoenix components.

I'm closing this for now thanks!
