### ISSUE TITLE
Add `after_render_template` lifecycle stage

### ISSUE THREAD

**Issue by leandrocp** [BeaconCMS/beacon#292]
A lifecycle stage that runs after the page is rendered:

- Should be async
- Should not affect page rendering time
- Failures on that stage should not crash the page

**Comment by AZholtkevych** [comment]
Could be useful for Plausible integration. Moving to backlog for now, since @TheFirstAvenger could have other implementation

**Comment by leandrocp** [comment]
Closing this one for now. Will reopen if needed.
