### ISSUE TITLE
Core -> General Improvements: Rename `layout.body` to `layout.template`

### ISSUE THREAD

**Issue by leandrocp** [BeaconCMS/beacon#311]
"template" is the correct term used to for fields storing a template as HEEx or Markdown, in this case for layouts we only support HEEx at the moment.

Follows the same pattern as `page.template`, which makes it easier to reuse code dealing with templates for both pages and layouts.

https://github.com/BeaconCMS/beacon/blob/fcbb5b5dea75d17db96aef78fb1b9988e1a0bffe/lib/beacon/content/layout.ex#L32

**Comment by gitkumi** [comment]
Can I take this? :)

Opened a PR:
https://github.com/BeaconCMS/beacon/pull/320
