### ISSUE TITLE
`beacon.install`: Don't allow sites starting with `beacon_`

### ISSUE THREAD

**Issue by APB9785** [BeaconCMS/beacon#333]
The installer will allow this invalid site name, injecting it into your app, but then it will cause failures when you try to setup and build the app.

**Comment by leandrocp** [comment]
See https://github.com/BeaconCMS/beacon/blob/main/lib/mix/tasks/install.ex

**Comment by edborsa** [comment]
https://github.com/BeaconCMS/beacon/pull/385/files

**Comment by leandrocp** [comment]
Closed by https://github.com/BeaconCMS/beacon/issues/333
