### ISSUE TITLE
Scroll position history bug

### ISSUE THREAD

**Issue by bcardarella** [BeaconCMS/beacon#340]
When navigating if a page doesn't scroll it doesn't set its scroll position for the history. Example:

https://github.com/BeaconCMS/beacon/assets/18524/86ad78ec-10e9-4f98-8434-6d07680cf391

However if the same steps are taken but a scroll event occurs the position is set properly. Example:

https://github.com/BeaconCMS/beacon/assets/18524/2f614333-8ecf-478e-b3bb-fb701ed6b37d

**Comment by leandrocp** [comment]
Duplicate of https://github.com/BeaconCMS/beacon/issues/123
