### ISSUE TITLE
Components and Pages: Create new layouts with a default template

### ISSUE THREAD

**Issue by leandrocp** [BeaconCMS/beacon#345]
When a new layout is created, its template should have the following default content:

```heex
<%= @inner_content %>
```

That's necessary to render the page content using that layout, so it starts with that default content to help users creating new layouts. But it won't be enforced for now, users could remove that line.

**Comment by edborsa** [comment]
Hey @leandrocp, I want to start contributing, haha.
And this one seems easy.

Here is the PR:
https://github.com/BeaconCMS/beacon/pull/383

(BTW, great talk on Elixir em Foco. I bought the "How to Open Source" book)

If there are any guidelines and tips you want to suggest, or changes, please let me know.

Best regards

**Comment by leandrocp** [comment]
Closed by https://github.com/BeaconCMS/beacon/pull/383
