### ISSUE TITLE
Small bug in Installation.md guide

### ISSUE THREAD

**Issue by mattvanhorn** [BeaconCMS/beacon#355]
The URL params will be passed with string keys, but the line with @beacon_path_params.blog_slug is looking for an atom as the key, and so will fail with a KeyError, like so:
```
(KeyError) key :blog_slug not found in: %{"blog_slug" => "my_first_post"}
```
I made a PR for it here: [https://github.com/BeaconCMS/beacon/pull/354](https://github.com/BeaconCMS/beacon/pull/354)

**Comment by leandrocp** [comment]
Fixed by https://github.com/BeaconCMS/beacon/pull/354
