### ISSUE TITLE
Page Builder: Featured pages component

### ISSUE THREAD

**Issue by leandrocp** [BeaconCMS/beacon#357]
Currently the featured blog posts section in the dockyard.com website (screenshot below) is managed by a custom database table and custom code but we want to expose that kind of content as a reusable component that will look like:

```heex
<BeaconWeb.Components.featured_pages />
```

That component can receive an `source` argument that is a function used to return a list of pages. It should be optional and the default implementation should be `Content.list_pages(site, per_page: 3, sort: :updated_at)`

`site` can be fetched from the live view process, see https://github.com/BeaconCMS/beacon/blob/cbe3bf7445cc559c96310593105e710366ed2cea/lib/beacon_web/components/components.ex#L28

<img width="1581" alt="Screenshot 2023-10-10 at 10 30 56 AM" src="https://github.com/BeaconCMS/beacon/assets/36407/00a116d7-30fe-41b0-8897-097fc1b8cde5">

**Comment by edborsa** [comment]
Hey, I created a PR for this one ;)

https://github.com/BeaconCMS/beacon/pull/388
