### ISSUE TITLE
Bug: PageModuleLoader calls wrong render function

### ISSUE THREAD

**Issue by scrusi** [BeaconCMS/beacon#378]
Hey, thank you for your great work.
In trying to check out Beacon, I noticed that https://github.com/BeaconCMS/beacon/pull/376/ seems to have introduced a bug that prevents pages from rendering, at least in the default setup.

Beacon.Loader.PageModuleLoader calls Beacon.Template.render/1 with assigns although it expects a page module. Calling render/2 seems to fix the issue, however I know too little about Beacon to submit a PR right now.

Beacon.Loader.PageModuleLoader:44
`
%Phoenix.LiveView.Rendered{} = rendered <- Beacon.Template.render(page_module, assigns) do
` 

Hope that helps

**Comment by krns** [comment]
I think I have the same problem. If I refresh the page fast enough, my page content eventually renders.

https://github.com/BeaconCMS/beacon/assets/7387295/11c7d8c5-e00f-4e11-959d-cf0a661481ec

**Comment by leandrocp** [comment]
My bad, a refactor gone wrong. It should be fixed by https://github.com/BeaconCMS/beacon/pull/380, please give it a try.
