### ISSUE TITLE
Enforce paths starting with a trailing slash `/`

### ISSUE THREAD

**Issue by leandrocp** [BeaconCMS/beacon#395]
URLs are by definition separated by `/` and usually they start with that separator, which means a root path is designed to be served at `/`.

Currently that's not enforced making the root path to be assigned to `""` which is not a big deal but we found that's causing some confusion on the new [Live Data feature](https://github.com/BeaconCMS/beacon/pull/363) where users have to input a path to create new assigns.

So we want to enforce that all paths must start with a trailing slash `/`

**Comment by APB9785** [comment]
Maybe the biggest hurdle here is we will have to do a data migration on dy-api page paths
