### ISSUE TITLE
Failed to resolve default tailwind config

### ISSUE THREAD

**Issue by leandrocp** [BeaconCMS/beacon#440]
The default config should resolve the `tailwind_config` with the path to https://github.com/BeaconCMS/beacon/blob/main/priv/tailwind.config.js.eex but it's either empty or invalid causing the following exception:

```
Make sure the provided file exists at "/app/_build/prod/lib/beacon/priv/tailwind.config.js.eex" and it contains <%= @beacon_content %> in the `cont
ent` section.
```

Reported at https://elixir-lang.slack.com/archives/C02T04D147M/p1711591088310979

**Comment by rubiagatra** [comment]
Let me take a look on the weekend
