### ISSUE TITLE
Core menu buttons just reload the page

### ISSUE THREAD

**Issue by peterjreynoldsii** [BeaconCMS/beacon#521]
![image](https://github.com/BeaconCMS/beacon/assets/39418872/6814f24a-c2a0-4ded-ab0d-efd71fa93d6a)

when I go to staging.dockyard.com and sign in, clicking any of the buttons on the dockyard_com menu just reload the page instead of taking me to options. Is this a personal account issue or is there an issue with the menu?

**Comment by leandrocp** [comment]
That was caused by lack of permission to access admin pages, I just fixed it. It should be give you a feedback instead of just reloading the page so I just added https://github.com/BeaconCMS/beacon_live_admin/issues/175 to the backlog. Closing this one, thanks!
