### ISSUE TITLE
Use a `DynamicSupervisor` for `Beacon`

### ISSUE THREAD

**Issue by leandrocp** [BeaconCMS/beacon#651]
Migrate from a traditional `Supervisor` to `DynamicSupervisor` so we have more control to manage sites (children).

**Comment by APB9785** [comment]
Regular `Supervisor` ends up fitting our use-case better here, as the site processes aren't temporary (using `DynamicSupervisor` implies that its children are temporary processes), and we still do have the possibility of `Supervisor.terminate_child/2` and `Supervisor.restart_child/2` if needed
