### ISSUE TITLE
igniter install: extra_applications and applications in use

### ISSUE THREAD

**Issue by bcardarella** [BeaconCMS/beacon#669]
Got this when generating a new project:

```
both :extra_applications and :applications was found in your mix.exs. You most likely want to remove the :applications key, as all applications are derived from your dependencies
```

**Comment by leandrocp** [comment]
Hi @bcardarella that message is actually caused by https://hex.pm/packages/oembed. I'm closing this one in favor of https://github.com/BeaconCMS/beacon/issues/676
