### ISSUE TITLE
Asset management (EXTERNAL)

### ISSUE THREAD

**Issue by AZholtkevych** [BeaconCMS/beacon#75]
As a PO, I want to store assets somewhere. Assets: images, videos, logos, files (all file types must be supported) as well as the CMS templates. We can use database (PostgreSQL for example) or Amazon S3, or other solutions here.
As well we have to have the functionality to manage assets (CRUD - create content, read content (search), update content, delete content)

- [ ] Research the proper storage for the assets
- [ ] Adding CRUD functionality (~12 days)

**Comment by bcardarella** [comment]
We are storing within the database, not externally.

**Comment by AZholtkevych** [comment]
DUPLICATING #31 . Closing
