### ISSUE TITLE
Beacon CMS doesn't work with Phoenix 1.7.0-rc.0

### ISSUE THREAD

**Issue by derpycoder** [BeaconCMS/beacon#87]
Hey Guys,

I'm excited about using Beacon CMS in my project.

I just created a new app using latest release candidate and when I tried to add `{:beacon, github: "beaconCMS/beacon"}` to mix file and ran `mix deps.get`, I got following error:

```elixir
❯ mix deps.get
* Updating beacon (https://github.com/beaconCMS/beacon.git)
origin/HEAD set to main
* Updating safe_code (https://github.com/TheFirstAvenger/safe_code.git)
origin/HEAD set to main
Resolving Hex dependencies...
#Incompatibility<#Term<your app>, cause: {:conflict, #Incompatibility<#Term<not phoenix_live_view 0.18.3 (optional)>, cause: {:conflict, #Incompatibility<#Term<the lock>, #Term<not phoenix_live_view 0.18.3 (optional)>, cause: :dependency>, #Incompatibility<#Term<your app>, #Term<not the lock>, cause: :dependency>}>, #Incompatibility<#Term<your app>, #Term<not phoenix_live_view ~> 0.17.5>, cause: :dependency>}>
Resolution completed in 0.048s
Because "the lock" specifies phoenix_live_view 0.18.3, phoenix_live_view 0.18.3 is required.
So, because your app depends on phoenix_live_view ~> 0.17.5, version solving failed.
** (Mix) Hex dependency resolution failed
```

___

```elixir
❯ elixir --version
Erlang/OTP 25 [erts-13.1.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Elixir 1.14.2 (compiled with Erlang/OTP 25)
```

**Comment by pascalwengerter** [comment]
@derpycoder from reading `So, because your app depends on phoenix_live_view ~> 0.17.5, version solving failed.` it looks like you'd need to bump the `phoenix_live_view` dependency in your own project? From what I read on https://github.com/phoenixframework/phoenix_live_view/blob/master/CHANGELOG.md it doesn't seem like breaking changes occured, so it should be straightforward to do :)

**Comment by jamiedumont** [comment]
When creating a new Phoenix app using the 1.7 RC and adding Beacon as a dependency, I'm getting the same error, but specifically it's `safe_code` which is one of Beacon's dependencies that's requiring `phoenix_live_view 0.17.5`.

Patching `safe_code`'s `mix.exs` to require `{:phoenix_live_view, "~> 0.18.3"}` seems to be all that's needed to get it to compile. I'll open a PR on `safe_code`

**Comment by TheFirstAvenger** [comment]
`safe_code` has been updated.

**Comment by leandrocp** [comment]
Thanks!
