### ISSUE TITLE
Documentation/screenshots

### ISSUE THREAD

**Issue by dolfinus** [BeaconCMS/beacon#93]
Hi.

Is it planned to add some documentation?
The required minimum is, IMHO, some screenshots of CMS UI, list of features, how to add content and change page appearance. For pro users it could be API spec, example of writing plugins and so on.

**Comment by leandrocp** [comment]
Hi @dolfinus, documentation is essential  to help drive adoption. The first step is adding `ex_doc` and a PR is welcome 🙂

**Comment by dolfinus** [comment]
That's not a great idea to advise someone who has no idea what this project is intended to do and capable of to build the documentation.

**Comment by leandrocp** [comment]
Actually I meant just installing `ex_doc` and adding the bare minimum config in `mix.exs` to get it working, that would be helpful. Writing guides with screenshots, writing doc/spec, and so on will be done as the project grows.

**Comment by leandrocp** [comment]
Hi @dolfinus just added `ex_doc` to the project and I'll be working on documentation as we move forward. Thanks.

**Comment by dolfinus** [comment]
Are you talking about https://hexdocs.pm/beacon/Beacon.html?

**Comment by leandrocp** [comment]
> Are you talking about https://hexdocs.pm/beacon/Beacon.html?

That's another project, BeaconCMS wasn't released yet thus you won't find it on hexpm. A release is planned soon and a more complete documentation will be available.
