### ISSUE TITLE
[BE] Page Meta tags

### ISSUE THREAD

**Issue by AZholtkevych** [BeaconCMS/beacon#99]
As a PO I would like to manage meta tags. We can have them preconfigured and be able to change. As well users can create meta tags by themselves. Meta tags could be for the whole page as well as for the piece of content. User has an ability to edit meta tags and delete them as well.

**Comment by leandrocp** [comment]
### Add support for page meta tags

At this moment beacon supports meta tags for layouts only, and we want to add support for page meta tags too.

Given a layout with meta tags (already supported):

```elixir
%{id: layout_id} =
 Layouts.create_layout!(%{
    site: "my_site",
    title: "Sample Home Page",
    meta_tags: %{"my-layout-meta-tag" => "layout-value"}
    # ... code omitted
})
```

And a page with meta tags (that will be implemented):

```elixir
  Pages.create_page!(%{
    path: "home",
    site: "my_site",
    layout_id: layout_id,
    meta_tags: %{"my-page-meta-tag" => "page-value"}
    # ... code omitted
```

The resulting html would be:

```html
<!-- code omitted and simplified -->
<html>
  <head>
    <meta name=”my-layout-meta-tag” content=”layout-value” />
    <meta name=”my-page-meta-tag” content=”page-value” />
  </head>
</html>
```

Both are optional.

**Comment by dukeweezo** [comment]
Hey, first of all, great project! 

I'm working on this, focusing on the functionality as described above (by @leandrocp), using `meta_tags(assigns)` (as used in `runtime.html.heex`), and related functions, as a guide.

Will have something to share in the next few days.

**Comment by AZholtkevych** [comment]
FYI @leandrocp

**Comment by leandrocp** [comment]
Closed by https://github.com/BeaconCMS/beacon/pull/109
